// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vijzgubyuhvmndyzwyrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpanpndWJ5dWh2bW5keXp3eXJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNTEyOTcsImV4cCI6MjA2MjcyNzI5N30.LfthVhMz-i7NHLvJwWAg0R7r2I9bxgouTJbdDq8IzJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);